### PR TITLE
Translate Admin GUI

### PR DESCRIPTION
**Pull request by gwenandres**
Hello, 

I create translation for admin interface. 

I try to keep the translation mechanism but I had to isolate the i18n function in a specific file (remove from server.py file). 

I let text in english in the german file in order to keep words in interface. Otherwise you have empty strings. 

Here is an example of translated interface. 

Screenshot 2022-12-07 at 18-15-07 Créer un thème - Administration QWC

Sorry for this big PR.... 

Have a good day, 

Gwendoline Andres

### CODE REVIEW

**Comment by manisandro** [comment]
Nice work! Would you be interested in adding a script like [1] to automatically update the translation file with new strings?

[1] https://github.com/qgis/qwc2/blob/master/scripts/updateTranslations.js

**Comment by gwenandres** [comment]
Thanks! 

Yes it's a good idea and I am interested in doing this script. Unfortunately I haven't time to do that before the end of the year but I can plan that for the beginning of 2023...

Do you think it is necessary to merge this PR ?

**Comment by gwenandres** [comment]
Hello @manisandro  1 year after, I have created the script which  automatically update the translation file with new strings.

What do you think about it ? 

I think this script should be run by developers before pushing on repository, that's why I add instructions in README file. 
If you prefer I can add it in the Dockerfile... 

Have a nice day :)

**Comment by manisandro** [comment]
Thanks for your work! Just one remark: some strings (especially the "Really delete" strings) are part of a larger string concatenated with a variable, but are translated in separate chunks. This makes it hard to translate them properly (i.e. in german). It would be better to translate them as one entire string and use a variable placeholder.

**Comment by gwenandres** [comment]
Hello @manisandro , today I work on your suggestion. 

Now translation are able to deal with string placeholder (one or more). 

I add the run of the translation script in DockerFile. I don't know if you think it was mandatory. 

Have a nice day

**Comment by manisandro** [comment]
@gwenandres Thanks! I don't think it is necessary to run the translation script in the Dockerfile, as it will not produce anything useful.

**Comment by manisandro** [comment]
Thanks!

**Pull request merged**
